import type { Metadata } from "next";

import "../globals.css";

export const metadata: Metadata = {
  title: "Cadastro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-full flex flex-col justify-center items-center">
      {children}
    </div>
  );
}
